<?php
/**
 * @var \League\Plates\Template $v
 * @var \Php\Domain\User\User|null $loginUser
 * @var array $errors
 */
?>
<html lang="ja">
<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<?php $v->insert('partials/header') ?>
<div class="container">
    <div class="row">
        <div class="col-12 mt-3">
            <?php foreach ($errors as $error): ?>
                <div class="alert alert-danger" role="alert">
                    <?= $error ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <?= $v->section('content') ?>
        </div>
    </div>
</div>
</body>
</html>
